/* Generated by automated build script */
#define SNAPSHOT
#define TEXTVER "Development snapshot 2019-02-22.ca90a36"
#define SSHVER "-Snapshot-2019-02-22.ca90a36"
#define BINARY_VERSION 0,70,1598,0
#define SOURCE_COMMIT "ca90a36bcd0bf078453a9027adf1fd3a216614eb"
